### ISSUE TITLE
Phase 2 milestone tracker

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#283]
To assist with this task:
1. Find an unassigned task in the list below
2. Send an email to me (glenl . glx @ gmail.com) with the issue number for the piece you wish to work on
3. Submit changes either with a GITHUB pull request or by email to my address

Issue #284  , [Divertimento II by MozartWA (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=261)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #285  , [Sonata No. 18 (1st Movement: Molto allegro) by MozartWA (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=356)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #286 , [Sonata No. 18 (2nd Movement: Adagio) by MozartWA (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=357)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #287 , [Sonata No. 18 (3rd Movement: Allegro assai) by MozartWA (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=358)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #288 , [Sonata in E Per Mandolino, e Basso by GiulianoG (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=362)
- [x] Assigned to Karsten
- [x] Pull request submitted

Issue #289 , [Sonata in Ess Per Mandolino, e Basso by GiulianoG (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=363)
- [x] Assigned to Karsten
- [x] Pull request submitted

Issue #290 , [Dies Irae by MozartWA (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=364)
- [x] Assigned to Francisco
- [x] Pull request submitted

Issue #291 , [Après un Rêve by FaureG (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=368)
- [x] Assigned to Francisco
- [x] Pull request submitted

Issue #292 , [Slumber My Darling by FosterSC (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=370)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #293 , [Hard Times Come Again No More by FosterSC (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=371)
- [x] Assigned to Javier
- [x] Pull request submitted

Issue #294 , [Fidelio Overture by BeethovenLv (at 2.0.1)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=377)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #295 , [Search-Light Rag by JoplinS (at 2.0.2)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=275)
- [x] Assigned to Federico
- [x] Pull request submitted

Issue #296 , [Prelude: Op. 28, No. 1 by ChopinFF (at 2.0.3)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=411)
- [x] Assigned to Javier
- [x] Pull request submitted

Issue #297 , [Fugues on the Magnificat III. 7. by PachelbelJ (at 2.0.3)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=420)
- [x] Assigned to Francisco Vila
- [x] Pull request submitted

Issue #298 , [Prelude by ScriabinA (at 2.0.3)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=445)
- [x] Assigned to Federico
- [x] Pull request submitted
