### ISSUE TITLE
Typesetting request - milestone tracker

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#355]
**To contribute to this typesetting request:**
- Select an unassigned work from the list below (open linked issues for details).
- Please limit your selections to what you can realistically complete by June 2014.
- Notify us via email for assignment: javier (at) ruiz-alma.com
- Refer to the [contribution page](http://www.mutopiaproject.org/contribute.html#contribute) and [Mutopia keyboard template](https://gist.github.com/dominicus/11064809) for needed headers and recommended spacing.
- LilyPond version 2.18 is preferred, but not mandatory.
- Reference selected must be a Public Domain edition.  Urtext or Non-PD references are not acceptable.
- Submit your contribution via pull-request or by email.

**Issue #352 - Chopin Ballade No.1 in G minor - Op23** (14 pages, 156 downloads/day)
- [x] Assigned to @dominicus
- [x] Pull-request submitted

**Issue #353 - Chopin Nocturne No. 3 - Op9** (9 pages, 108 downloads/day)
- [x] Assigned to @glenl 
- [x] Pull-request submitted

**Issue #354 - Rachmaninoff 10 Preludes - Op23** (48 pages, 80 downloads/day)
- [ ] 9 of 10 assigned (see issue for still-unassigned listings)

**Issue #356 - Mussorgsky "Pictures at an Exhibition" Movements 2-15** (38 pages, 73 downloads/day) 
- [x] Assigned to @ksnortum
- [x] Pull-request submitted

**Issue #357 - Hanon "The Virtuoso Pianist" Part 1 (1-20)** (20 pages, 69 downloads/day)
- [x] Assigned to @stevetnz
- [x] Pull-request submitted

**Issue #358 - Debussy - 12 Préludes (Book 1)** (52 pages, 63 downloads/day)
- [ ] 4 of 12 assigned (see issue for still unassigned listings)

**Issue #359 - Mendelssohn - Violin Concerto in Emin (solo) Op64** (14 pages, 55 downloads/day)
- [x] Assigned to @slacy
- [ ] Pull-request submitted

**Issue #360 - Schubert's "Winterreise" (24 songs) Op89** (73 pages, 54 downloads/day)
- [x] Unclaimed, now closed

**Issue  #361 - Elgar "Salut d'amour" Op12 (violin and piano)** (4 pages, 50 downloads/day)
- [x] Unclaimed, now closed

**Issue #362 - Paganini 24 Caprices for Solo Violin Op1** (30+ pages, 40 downloads/day)
- [x] Assigned to Samuel Rummel
- [ ] Pull-request submitted

**Issue #363 - Bach's Violin Concerto in A minor (violin solo) BWV1041** (6 pages, 35 downloads/day)
- [x] Assigned to _@dominicus_
- [x] Pull-request submitted

**Issue #364 - Debussy's Deuxième Arabesque CD 74 L.66** (5 pages, 33 downloads/day)
- [x] Assigned to _@ksnortum_
- [x] Pull-request submitted

**Comment by dominicus** [comment]
Milestone is now closed
