### ISSUE TITLE
New: Debussy - 12 Préludes (Book 1) - CD 125 L.117

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#358]
- [IMSLP Ref Page](http://imslp.org/wiki/Pr%C3%A9ludes_%28Book_1%29_%28Debussy,_Claude%29)
- Reference: Schirmer, n.d.(ca.1990) IMSLP [#59704](http://imslp.org/wiki/Special:ImagefromIndex/59704) and [#59705](http://imslp.org/wiki/Special:ImagefromIndex/59705)
- IMSLP Popularity (downloads/day): 63
- YearComposed/Style/Instrument: 1910/Romantic/Piano
- Comments: 52 pages.

Prélude 1
- [x] assigned to @dominicus
- [x] pull-request submitted (#397)

Prélude 2
- [x] assigned to @ksnortum
- [x] pull-request submitted (#521)

Prélude 3
- [x] assigned to @glenl
- [x] pull-request submitted (#490)

Prélude 4
- [x] assigned to @ksnortum 
- [x] pull-request submitted (#562)

Prélude 5
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 6
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 7
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 8
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 9
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 10
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 11
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

Prélude 12
- [ ] assigned to _unassigned_
- [ ] pull-request submitted

**Comment by ksnortum** [comment]
Well, I'm going to get started on Prelude 4 -- if you would assign it to me.  We can talk about the changes we need to make to get this piece to compile into both individual pieces and a book whenever you want.  I'd like to see what Glen's done too.

**Comment by dominicus** [comment]
I've noted the assignment of prel 4.  Thanks for keeping our momentum here.  I'll provide an update on the results of my collection trials to the discussion of #383.
