### ISSUE TITLE
Phase 3 updates, the milestone tracker

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaProject#435]
This is the milestone tracker issue for the Phase 3 updates.

To assist with this task:
1. Find an unassigned task in the list below
2. Send an email to me (glenl . glx @ gmail.com) with the issue number for the piece you wish to work on
3. Submit changes either with a GITHUB pull request or by email to my address

Issue #436, [My Mother's Old Red Shawl by MorelandC (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=430)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #437, [I Cannot Sing the Old Songs by Claribel (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=431)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #438, [The Three Fishers by HullahJ (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=429)
- [x] Assigned to Paul Morris
- [x] Pull request submitted

Issue #439, [Preludio by SanzG (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=380)
- [x] Assigned to @fedelibre
- [x] Pull request submitted

Issue #440, [Do They Think of Me At Home? by GloverCW (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=437)
- [x] Assigned to @doughdemon 
- [x] Pull request submitted

Issue #441, [Sally in Our Alley by CareyH (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=432)
- [x] Assigned to @doughdemon 
- [x] Pull request submitted

Issue #442, [The Blue Alsatian Mountains by AdamsS (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=440)
- [x] Assigned to @doughdemon 
- [x] Pull request submitted

Issue #443, [When the Swallows Homeward Fly (Agathe) by AbtF (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=439)
- [x] Assigned to @doughdemon 
- [x] Pull request submitted

Issue #444, [Ballade number 4 by ChopinFF (at 2.1.0)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=422)
- [x] Assigned to Abel Cheung
- [x] Pull request submitted

Issue #445, [The Last Rose of Summer (Martha) by MooreT (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=434)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #446, [12 Duets (No. 1: Allegro) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=390)
- [x] Assigned to Francisco Vila
- [x] Pull request submitted

Issue #447, [12 Duets (No. 10: Andante) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=399)
- [x] Assigned to Felix Janda
- [x] Pull request submitted

Issue #448, [12 Duets (No. 11: Menuetto) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=400)
- [x] Assigned to Felix Janda
- [x] Pull request submitted

Issue #449, [12 Duets (No. 12: Allegro) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=401)
- [x] Assigned to Felix Janda
- [x] Pull request submitted

Issue #450, [12 Duets (No. 2: Menuetto) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=391)
- [x] Assigned to Knute Snortum
- [x] Pull request submitted

Issue #451, [12 Duets (No. 3: Andante) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=392)
- [x] Assigned to Francisco Vila
- [x] Pull request submitted

Issue #452, [12 Duets (No. 4: Polonaise) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=393)
- [x] Assigned to Francisco Vila
- [x] Pull request submitted

Issue #453, [12 Duets (No. 5: Larghetto) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=394)
- [x] Assigned to Javier Ruiz-Alma
- [x] Pull request submitted

Issue #454, [12 Duets (No. 6: Menuetto) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=395)
- [x] Assigned to Javier Ruiz-Alma
- [x] Pull request submitted

Issue #455, [12 Duets (No. 7: Adagio) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=396)
- [x] Assigned to Knute Snortum
- [x] Pull request submitted

Issue #456, [12 Duets (No. 8: Allegro) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=397)
- [x] Assigned to Knute
- [x] Pull request submitted

Issue #457, [12 Duets (No. 9: Menuetto) by MozartWA (at 2.1.7)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=398)
- [x] Assigned to Felix Janda
- [x] Pull request submitted

Issue #458, [The Old Oaken Bucket by KiallmarkGF (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=436)
- [x] Assigned to @fedelibre 
- [x] Pull request submitted

Issue #459, [There's Music in the Air by RootGF (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=427)
See piece of same title at #461
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #460, [The Vacant Chair by RootGF (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=426)
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #461, [There's Music in the Air by RootGF (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=428)
Note: see also #459
- [x] Assigned to glenl
- [x] Pull request submitted

Issue #462, [Home, Sweet Home by BishopHR (at 2.1.34)](http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=435)
- [x] Assigned to glenl
- [x] Pull request submitted
